#ifndef SIGNALS_H
#define SIGNALS_H

enum {
	USER_IN_SIG = USER_SIG,
	TIMEOUT_SIG,
	UPDATE_FRAME_TIMEOUT_SIG,
	UPDATE_LVL_TIMEOUT_SIG,
	APPLE_TIMEOUT_SIG,
	ENEMY_TIMEOUT_SIG,
	PWR_TIMEOUT_SIG,
	CLR_PWR_TIMEOUT_SIG,
	REMOVE_DOUBLE_TIMEOUT_SIG,
	REMOVE_SLOW_TIMEOUT_SIG,
	ELAPSED_TIMEOUT_SIG,
	SCREEN_FRAME_SIG,
};

#endif
